project_id = "dbxaamdirxjrbolsegwz"

[functions.get-reportei-metrics]
verify_jwt = false

[functions.list-reportei-ads]
verify_jwt = false

[functions.verify-jira-user]
verify_jwt = false

[functions.validate-download]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false

[functions.list-canva-blocks]
verify_jwt = false

[functions.generate-email-magic]
verify_jwt = true

[functions.generate-efi-report]
verify_jwt = false

[functions.jira-login]
verify_jwt = false

[functions.extract-pdf-content]
verify_jwt = true

[functions.pdf-extraction-webhook]
verify_jwt = false

[functions.create-jira-task]
verify_jwt = true

[functions.delete-jira-task]
verify_jwt = true

[functions.create-jira-epic]
verify_jwt = true

[functions.og-metadata]
verify_jwt = false
