project_id = "dbxaamdirxjrbolsegwz"

[functions.verify-jira-user]
verify_jwt = false

[functions.validate-download]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false

[functions.list-canva-blocks]
verify_jwt = false
