project_id = "dbxaamdirxjrbolsegwz"

[functions.get-reportei-metrics]
verify_jwt = false

[functions.list-reportei-ads]
verify_jwt = false

[functions.verify-jira-user]
verify_jwt = false

[functions.validate-download]
verify_jwt = false

[functions.replicate-webhook]
verify_jwt = false

[functions.list-canva-blocks]
verify_jwt = false

[functions.generate-email-magic]
verify_jwt = true

[functions.generate-efi-report]
verify_jwt = false

[functions.jira-login]
verify_jwt = false
